### ISSUE TITLE
Return a blank report

### ISSUE THREAD

**Issue by appleman1** [andgineer/docker-allure#1]
I run the container this way.
`docker run -d -v result-saxon:/allure-results -v reports:/allure-report -p 8000:80  --name allure allure ./allure generate /allure-results -o /allure-report --clean`
as a result, an empty allure-report is formed, please tell me what am I doing wrong?

**Comment by andgineer** [comment]
I understand I am slighly late with the answer ;)
I think the problem is in the paths - Docker expects absolute paths and you gave relative `result-saxon`, `reports`.

I tested instructions in README and they work for me.
Also add additional details in README, hope that helps
